### ISSUE TITLE
typos in the preprint

### ISSUE THREAD

**Issue by Tsingularity** [SHI-Labs/UltraSR-Arbitrary-Scale-Super-Resolution#1]
Hi, thanks for the good work!

I noticed the following typos in the pre-print, hope this could help!

- page 6, right column, should be 'figure 5' instead of 'table 5'
- page 6, the last two paragraphs are duplicate

**Comment by xingqian2018** [comment]
Hi, thanks a lot for pointing it out. We will have it fixed soon.

Sincerely.
